### ISSUE TITLE
info_url should link direct to application

### ISSUE THREAD

**Issue by henare** [JasonThomasData/Wyndham_City_Council#2]
Instead of an index page. It looks like it's possible, e.g. https://eproperty.wyndham.vic.gov.au/ePropertyPROD/P1/eTrack/eTrackApplicationDetails.aspx?r=P1.WEBGUEST&f=$P1.ETR.APPDET.VIW&ApplicationId=WYP9341%2f16

**Comment by JasonThomasData** [comment]
Damn this link has a zero width space, how to fix that again? ARGH

**Comment by henare** [comment]
[`.strip`](http://ruby-doc.org/core-2.3.1/String.html#method-i-strip) doesn't work?

**Comment by JasonThomasData** [comment]
john@john-Lenovo-G50-45:~/Desktop/OAF_planning_alerts/Wyndham_City_Council$ ruby scraper.rb
scraper.rb:68: syntax error, unexpected tIDENTIFIER, expecting end-of-input
...eTrackApplicationDetails.aspx?r=P1.WEBGUEST&f=$P1.ETR.APPDET...
...                               ^

**Comment by JasonThomasData** [comment]
```
link_to_decision = 
"https://eproperty.wyndham.vic.gov.au/ePropertyPROD/P1/eTrack/eTrackApplicationDetails.aspx?r=P1.WEBGUEST&f=%24P1.ETR.APPDET.VIW&ApplicationId=WYP9341%2f16"
```

I'm going absolutely mad, there's nothing wrong with this string is there?

**Comment by henare** [comment]
I've never seen that problem before. Is it a problem with string escaping or something?

**Comment by henare** [comment]
Seems fine to me:

```
henare@mana:~ rvm:(ruby-2.2.0) $ irb
2.2.0 :001 > link_to_decision = 
2.2.0 :002 >   "https://eproperty.wyndham.vic.gov.au/ePropertyPROD/P1/eTrack/eTrackApplicationDetails.aspx?r=P1.WEBGUEST&f=%24P1.ETR.APPDET.VIW&ApplicationId=WYP9341%2f16"
 => "https://eproperty.wyndham.vic.gov.au/ePropertyPROD/P1/eTrack/eTrackApplicationDetails.aspx?r=P1.WEBGUEST&f=%24P1.ETR.APPDET.VIW&ApplicationId=WYP9341%2f16" 
2.2.0 :003 > 
```
