### ISSUE TITLE
Remove debugging

### ISSUE THREAD

**Issue by henare** [JasonThomasData/Wyndham_City_Council#3]
A little logging is good but there's pretty verbose debugging. I think it should be at least commented out before we fork this.

**Comment by JasonThomasData** [comment]
Which code are you talking about? Not sure what you mean sorry.

**Comment by henare** [comment]
When I run the scraper I get heaps of output. I don't think the output should be so verbose.

**Comment by JasonThomasData** [comment]
Righto, FYI I used Mechanize and Ruby so I ccould avoid reinventing the wheel. That was the code that I found on this scraper, so I assume it's on others too.

https://github.com/JasonThomasData/casey/blob/master/scraper.rb

I'll remove it but I think there must be quite a few like that on Morph

**Comment by henare** [comment]
That one doesn't have any debugging I can see: https://github.com/planningalerts-scrapers/casey/blob/master/scraper.rb

> I'll remove it but I think there must be quite a few like that on Morph

Can you link to any examples?

**Comment by JasonThomasData** [comment]
You are talking about the puts statements inside the block that saves the data aren't you?

`puts "Skipping already saved record " + record['council_reference']`

That was the issue with this repo?

**Comment by JasonThomasData** [comment]
So, here's some random scraper, happens to be Blacktown, with two different puts statements.
https://github.com/planningalerts-scrapers/blacktown_city/blob/master/scraper.rb

**Comment by henare** [comment]
I guess it was the whole record being dumped out, yes? `puts record`

> So, here's some random scraper, happens to be Blacktown, with two different puts statements.

And does that dump heaps of output every run, or something more terse and useful?

https://morph.io/planningalerts-scrapers/blacktown_city

**Comment by JasonThomasData** [comment]
OK, I find dumping the record useful, but I see your point. Anyway, the last commit fixed it so all good.
